FROM openjdk:17.0

LABEL maintainer="akshay"

ADD target/Hystrix-Dashboard-0.0.1-SNAPSHOT.jar Hystrix-Dashboard-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java" , "-jar" , "Hystrix-Dashboard-0.0.1-SNAPSHOT.jar"]

EXPOSE 9009