server:
  port: 9000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
            allowCredentials: true
            allowedHeaders: "*"

      routes:
        # Route For User Services
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/public/**,/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: UserService
                fallbackuri: forward:/userfallback
            - name: Retry
              args:
                name: UserService

        # Route For Product Service
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**,/category/**,/sub-category/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackuri: forward:/productfallback
            - name: Retry
              args:
                name: ProductService

        # Route For Cart Service
        - id: CartService
          uri: lb://CartService
          predicates:
            - Path=/cart/**,/cartItems/**,/coupon/**
          filters:
            - name: CircuitBreaker
              args:
                name: CartService
                fallbackuri: forward:/cartfallback
            - name: Retry
              args:
                name: CartService
        
        # Route For Order Service
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: OrderService
                fallbackuri: forward:/orderfallback
            - name: Retry
              args:
                name: OrderService

        # Route For Wishlist Service
        - id: WishListService
          uri: lb://WishListService
          predicates:
            - Path=/wishlist/**
          filters:
            - name: CircuitBreaker
              args:
                name: WishListService
                fallbackuri: forward:/wishlistfallback
            - name: Retry
              args:
                name: WishListService

# Hystrix
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

# Eureka Server Configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

resilience4j:
  # CircuitBreaker Module Configuration
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      CartService:
        baseConfig: default
      UserService:
        baseConfig: default
      ProductService:
        baseConfig: default
      OrderService:
        baseConfig: default
      WishListService:
        baseConfig: default

  # Retry Module
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 3s
    instances:
      CartService:
        baseConfig: default
      UserService:
        baseConfig: default
      ProductService:
        baseConfig: default
      OrderService:
        baseConfig: default
      WishListService:
        baseConfig: default
  
  # Bulkhead Module
  #  bulkhead:
  #    configs:
  #      default:
  #        maxConcurrentCalls: 100
  #    instances:
  #      CartService:
  #        baseConfig: default
  #      UserService:
  #        baseConfig: default
  #      ProductService:
  #        baseConfig: default
  #      OrderService:
  #        baseConfig: default
  #      WishListService:
  #        baseConfig: default

  # Rate limiter module
  #  ratelimiter:
  #    configs:
  #      default:
  #        registerHealthIndicator: false
  #        limitForPeriod: 5
  #        limitRefreshPeriod: 1s
  #        timeoutDuration: 0s
  #        eventConsumerBufferSize: 50
  #    instances:
  #      CartService:
  #        baseConfig: default
  #      UserService:
  #        baseConfig: default
  #      ProductService:
  #        baseConfig: default
  #      OrderService:
  #        baseConfig: default
  #      WishListService:
  #        baseConfig: default
  
  # Timelimiter module
  #  timelimiter:
  #    configs:
  #      default:
  #        cancelRunningFuture: false
  #        timeoutDuration: 2s
  #    instances:
  #      CartService:
  #        baseConfig: default
  #      UserService:
  #        baseConfig: default
  #      ProductService:
  #        baseConfig: default
  #      OrderService:
  #        baseConfig: default
  #      WishListService:
  #        baseConfig: default