# Application's Port
server:
  port: 9003

spring:
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CartService?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: root
    password: root

  # JPA , Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      ddl: true
    show-sql: true

  # Zipkin Server Configuration
  zipkin:
    base-url: http://127.0.0.1:9411/

  # Spring Boot Admin Client
  boot:
    admin:
      client:
        url:
          - http://localhost:8761/admin

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka Server Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true